# Generated by Django 3.2.12 on 2022-06-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0043_auto_20220606_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='class_seans',
            field=models.IntegerField(choices=[[1, 'Тематический концерт'], [2, 'Спектакль'], [3, 'Концерная программа'], [4, 'Выставка'], [5, 'Театрализированное представление'], [6, 'Народное гуляние'], [7, 'Конкурс, смотр'], [8, 'Дискотека'], [9, 'Шествие'], [10, 'Кино - Мультфильм'], [11, 'Кино - Приключение'], [12, 'Кино - Драма'], [13, 'Кино - Онлайн'], [14, 'Кино - Детектив'], [15, 'Кино - онлайн'], [16, 'Кино - Ужасы']], default=3),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='jNlqzuiZokYrAQg', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=1278, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loock_like',
            field=models.IntegerField(choices=[[1, 'Тематический концерт'], [2, 'Спектакль'], [3, 'Концерная программа'], [4, 'Выставка'], [5, 'Театрализированное представление'], [6, 'Народное гуляние'], [7, 'Конкурс, смотр'], [8, 'Дискотека'], [9, 'Шествие'], [10, 'Кино - Мультфильм'], [11, 'Кино - Приключение'], [12, 'Кино - Драма'], [13, 'Кино - Онлайн'], [14, 'Кино - Детектив'], [15, 'Кино - онлайн'], [16, 'Кино - Ужасы']], default=3),
        ),
        migrations.CreateModel(
            name='Tegs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя тега')),
                ('events', models.ManyToManyField(to='myapp2.DATA_ALL_SEANSES')),
            ],
            options={
                'verbose_name': 'Тэг_для_поиска',
                'verbose_name_plural': 'Тэги_для_поиска',
            },
        ),
    ]
