# Generated by Django 3.2.12 on 2022-06-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0047_auto_20220618_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.IntegerField(choices=[[1, 'Тематический концерт'], [2, 'Спектакль'], [3, 'Концертная программа'], [4, 'Выставка'], [5, 'Театрализированное представление'], [6, 'Народное гуляние'], [7, 'Конкурс, смотр'], [8, 'Дискотека'], [9, 'Шествие'], [10, 'Кино - Мультфильм'], [11, 'Кино - Приключение'], [12, 'Кино - Драма'], [13, 'Кино - Онлайн'], [14, 'Кино - Детектив'], [15, 'Кино - Комедия'], [16, 'Кино - Ужасы']], default=1),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='class_seans',
            field=models.IntegerField(choices=[[1, 'Тематический концерт'], [2, 'Спектакль'], [3, 'Концертная программа'], [4, 'Выставка'], [5, 'Театрализированное представление'], [6, 'Народное гуляние'], [7, 'Конкурс, смотр'], [8, 'Дискотека'], [9, 'Шествие'], [10, 'Кино - Мультфильм'], [11, 'Кино - Приключение'], [12, 'Кино - Драма'], [13, 'Кино - Онлайн'], [14, 'Кино - Детектив'], [15, 'Кино - Комедия'], [16, 'Кино - Ужасы']], default=3),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='ETLnBKarvQdMpZe', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=525, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loock_like',
            field=models.IntegerField(choices=[[1, 'Тематический концерт'], [2, 'Спектакль'], [3, 'Концертная программа'], [4, 'Выставка'], [5, 'Театрализированное представление'], [6, 'Народное гуляние'], [7, 'Конкурс, смотр'], [8, 'Дискотека'], [9, 'Шествие'], [10, 'Кино - Мультфильм'], [11, 'Кино - Приключение'], [12, 'Кино - Драма'], [13, 'Кино - Онлайн'], [14, 'Кино - Детектив'], [15, 'Кино - Комедия'], [16, 'Кино - Ужасы']], default=3),
        ),
    ]
