# Generated by Django 3.2.12 on 2022-06-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0048_auto_20220619_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pol',
            field=models.CharField(default='Н', max_length=3, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='wzdJgsnjQLNUROf', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=936, verbose_name='Цена билета'),
        ),
    ]
