# Generated by Django 3.2.12 on 2022-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0051_auto_20220619_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='ckzKQmfNdZwUAGu', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=1443, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.IntegerField(choices=[[1, 'Кемерово'], [2, 'Новосибирск'], [3, 'Новокузнецк'], [4, 'Москва']], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='pol',
            field=models.IntegerField(choices=[[1, 'Не важно'], [2, 'Мужской'], [3, 'Женский']], default=1),
        ),
    ]
