# Generated by Django 3.2.12 on 2022-06-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0052_auto_20220619_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='odYjpqbCJhInglP', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=1205, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.IntegerField(choices=[[1, 'Кемерово'], [2, 'Новосибирск'], [3, 'Новокузнецк'], [4, 'Москва'], [5, 'Томск']], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=25, verbose_name='Никнейм пользователя'),
        ),
    ]
