# Generated by Django 3.2.12 on 2022-07-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0053_auto_20220627_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='avtkFOclyxSCsMP', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=330, verbose_name='Цена билета'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='list_frends',
        ),
        migrations.AddField(
            model_name='user',
            name='list_frends',
            field=models.ManyToManyField(blank=True, related_name='_myapp2_user_list_frends_+', to='myapp2.USER'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='list_req_frends',
        ),
        migrations.AddField(
            model_name='user',
            name='list_req_frends',
            field=models.ManyToManyField(blank=True, related_name='_myapp2_user_list_req_frends_+', to='myapp2.USER'),
        ),
    ]
