# Generated by Django 3.2.12 on 2022-07-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0054_auto_20220701_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_all_seanses',
            name='ident_key',
            field=models.CharField(default='qUGkdjhpOuYBDQr', max_length=20, verbose_name='Специальный код сеанса'),
        ),
        migrations.AlterField(
            model_name='data_all_seanses',
            name='summa',
            field=models.IntegerField(default=866, verbose_name='Цена билета'),
        ),
        migrations.RemoveField(
            model_name='seans',
            name='seanses',
        ),
        migrations.AddField(
            model_name='seans',
            name='seanses',
            field=models.ManyToManyField(to='myapp2.DATA_ALL_SEANSES'),
        ),
    ]
